// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;
